spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-186.railway.app:5822/railway
    username: postgres
    password: f2K0EEMj3R46N4QRWbqU
    name: spring-blog

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes